{% set version = "0.4.1" %}

package:
  name: alphacsc
  version: {{ version }}

source:
  url: https://github.com/alphacsc/alphacsc/archive/{{ version }}.tar.gz
  sha256: 3981eaddbeaf94a3ec42754983ee6371d4f6c021aae06f7a05b8c2f32ab1fc11
  patches:
    - patches/001-remove_sporco_files_from_package.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - pip
    - numpy
    - cython
  run:
    - python
    - mne-base
    - numba
    - {{ pin_compatible('numpy') }}
    - scipy
    - joblib
    - matplotlib-base
    - scikit-learn

test:
  imports:
    - alphacsc
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/alphacsc/alphacsc
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Convolution dictionary learning for time-series.'
  description: |
    This is a library to perform shift-invariant sparse
    dictionary learning, also known as convolutional
    sparse coding (CSC), on time-series data. It is particularly
    adapted for MEEG data.
  doc_url: https://alphacsc.github.io/
  dev_url: https://github.com/alphacsc/alphacsc

extra:
  recipe-maintainers:
    - tommoral
